# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0c5f480392baecd25864e403da32dff517fe12fa1b454af581638d4084a2dea5b63d5d3c376ca177039e50b882e18ecdb456897c256a0ef22a6376893e433bf4

test:
  secret_key_base: 6953ae62bf0c0b8f517b6ec6e99fc6bc9ba174e3878ff19ae3661a1cf7f840a1dd95667e6766cd73da448bfcb51649b15a6e1a3b200636ddb9d52bb67f366f58

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
