# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c8ba7431e69bbfd6977c7bba29dd44d810b5c3c871037da83f7f214fd477d3a6229d58b8fd1b8b01e7bafa6c15117bbfa3c6c2bbb93a2df4df9eade5c37dad90

test:
  secret_key_base: 3863d77d6cdbab6a46993757d6d93f8b5dede5d9a4ae71ce3cdb9afad135e52ba3c58ecaf732278434b88c3dd84ef48b6d032ee249409b830d7db50295cd0d76

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
